### ISSUE TITLE
FileManager tab not available

### ISSUE THREAD

**Issue by ignaworn** [Salandora/OctoPrint-FileManager#1] opened 2015-12-13 20:57 UTC
As discussed here https://github.com/foosel/OctoPrint/issues/1142 FileManager Tab is not appearing in the main page. I've tried disabling all the other plugins and did not work either.

Plugin Version: FileManager (0.1.0)
OctoPrint Version: 1.3.0.dev761+g28eb436 (devel branch)
Browser: Google Chrome Version 47.0.2526.80 m

Octoprint.log http://pastebin.com/gzEMi3cn

Screenshots:
![capture](https://cloud.githubusercontent.com/assets/6243125/11769297/e24540e2-a1c2-11e5-96ad-17b34f0a09ce.PNG)
![capture2](https://cloud.githubusercontent.com/assets/6243125/11769298/e246073e-a1c2-11e5-8881-72bbe13925ce.PNG)

Thank you!

**Comment by Salandora** [comment] 2015-12-13 21:09
That's very very interesting...
I can see that Octoprint is loading the FileManager  plugin correctly.
At least it looks like.
I gonna try to reproduce this.
Might be a bug with the version check I implemented....
If you like to test you can comment 
https://github.com/Salandora/OctoPrint-FileManager/blob/master/octoprint_filemanager/__init__.py#L402-L404
this lines in you local install ( /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_filemanager)

**Comment by ignaworn** [comment] 2015-12-13 21:16
Excellent, I've added a # in each line you mentioned, restarted OctoPrint and voila!
Thank you very much!

Screenshot
![capture3](https://cloud.githubusercontent.com/assets/6243125/11769421/82186700-a1c5-11e5-9c06-b7803ee1a654.PNG)

**Comment by Salandora** [comment] 2015-12-13 21:19
Thanks for spotting and testing this. Guess I have to recheck the compatibility check then. :-/ very strange for me it worked when I tested it... hmm

**Comment by Salandora** [comment] 2015-12-13 23:02
I found the bug, it occured only with a version of setuptools wich gives back a tuple instead of an object.
I fixed it, updated the Version to 0.1.1 and deleted 0.1.0.
Please report back if it now works for you.

**Comment by ignaworn** [comment] 2015-12-13 23:02
Tested the latest commit https://github.com/Salandora/OctoPrint-FileManager/commit/5ceddcac68f9a3bf2a085bcfb07d9d735bd73128 and worked flawlessly. 

I think this issue can be closed. Thank you for helping

**Comment by Salandora** [comment] 2015-12-13 23:02
Lol this was a quick anser. Closing this then ;-)

**Closed by Salandora** 2015-12-13 23:02 UTC
